-- Generated by skillsfuture_to_greygigz.py
-- Source: jobsandskills-skillsfuture-skills-framework-dataset.xlsx
-- Generation Time: 2026-09-29 00:00:00

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Table structure for table `services`
--

CREATE TABLE `services` (
  `id` int UNSIGNED NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `url` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `meta_title` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `meta_desc` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `meta_keywords` varchar(200) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `image` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_general_ci,
  `user_id` int NOT NULL DEFAULT '0',
  `status` enum('0','1') COLLATE utf8mb4_general_ci NOT NULL DEFAULT '0' COMMENT '0 => inactive, 1 => active',
  `rating` decimal(10,0) DEFAULT NULL,
  `display_order` int DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `services`
--

INSERT INTO `services` (`id`, `name`, `url`, `meta_title`, `meta_desc`, `meta_keywords`, `image`, `description`, `user_id`, `status`, `rating`, `display_order`, `created_at`, `updated_at`) VALUES
(1, 'Industry', 'Industry', 'Industry', 'Industry', 'Industry', NULL, NULL, 0, '1', 5, 1, '2025-12-16 11:18:30', '2024-08-05 23:41:59'),
(2, 'Function', 'Function', 'Function', 'Function', 'Function', NULL, NULL, 0, '1', 5, 2, '2025-12-16 11:18:32', '2024-06-21 02:38:00'),
(3, 'Subject', 'Subject', 'Subject', 'Subject', 'Subject', NULL, NULL, 0, '1', 5, 3, '2025-12-16 11:18:56', '2024-06-21 02:38:03'),
(4, 'Others', 'Others', 'Others', 'Others', 'Others', NULL, NULL, 0, '1', 5, 4, '2025-12-16 17:48:00', '2024-06-21 02:38:03');

--
-- Indexes for table `services`
--
ALTER TABLE `services`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for table `services`
--
ALTER TABLE `services`
  MODIFY `id` int UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
